sudo: required
language: R
cache: packages
r_github_packages:
  - lbartnik/subprocess
env:
  matrix:
  - NOT_CRAN=true
r:
  - oldrel
  - release
  - devel
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); covr::codecov()'
